# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"create_img_dict_from_folder": "00_ratioimage.ipynb",
         "measure_region_props_to_tidy_df": "00_ratioimage.ipynb",
         "num_div_denom_measure_region_props_to_tidy_df": "00_ratioimage.ipynb"}

modules = ["ratioimage.py"]

doc_url = "https://morriso1.github.io/ratioimage/"

git_url = "https://github.com/morriso1/ratioimage/tree/master/"

def custom_doc_links(name): return None
