# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://morriso1.github.io/ratioimage/"

git_url = "https://github.com/morriso1/ratioimage/tree/master/"

def custom_doc_links(name): return None
